channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.16.3
  - matplotlib=3.3.2
  - pillow=6.2.1
  - earthengine-api=0.1.231
  - gdal=2.3.3
  - pandas=0.24.2
  - geopandas=0.4.1
  - pytz=2020.1
  - scikit-image=0.15.0
  - scikit-learn=0.20.3
  - shapely=1.6.4
  - scipy=1.2.1
  - astropy=3.2.1
  - spyder
  - notebook